name: CD - Staging (Render)

on:
  workflow_run:
    workflows: ["CI"]            # must match your CI workflow's `name: CI`
    types: [completed]

jobs:
  deploy-to-render:
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        (github.event.workflow_run.head_branch == 'ci-setup' ||
         github.event.workflow_run.head_branch == 'main')
      }}
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ secrets.STAGING_URL }}    
    steps:
      - name: Trigger Render deploy hook
        run: |
          set -e
          curl -fsS -X POST \
            -H "Content-Type: application/json" \
            --retry 5 --retry-delay 5 --max-time 120 \
            -d "{\"ref\":\"${{ github.event.workflow_run.head_branch }}\",\"sha\":\"${{ github.event.workflow_run.head_sha }}\",\"actor\":\"${{ github.event.workflow_run.actor.login }}\"}" \
            "${{ secrets.DEPLOY_HOOK_URL }}"
